Group failing spec by error message
nebulab/failing_spec_detector pull request #1
Opened 2023-11-29 12:01 UTC by safafa

## Description:

This Pr adds a custom rspec formatter, allows us to detect failing specs and group them by exception. the formatter prints the results in a text file.

## How to test: 

To test this on a rails project:
Add the gem to the Gemfile then the run rspec command using this flags: 
`bundle exec rspec --require failing_spec_detector/failing_spec_formatter.rb  --format FailingSpecDetector::FailingSpecFormatter`

2023-11-29 15:30 UTC, DanielePalombo reviewed
Do you mind updating the README with the instruction to configure the formatted?

2023-11-30 10:56 UTC, MassimilianoLattanzio approved these changes
Everything looks fine to me!

Later I'll try it in my application.

2023-12-04 09:05 UTC, DanielePalombo requested changes
This is not published on rubygems yet, do you mind writing the right installation instructions?

```ruby
gem 'failing_spec_detector', github: 'nebulab/failing_spec_detector'
```

What do you think adding an example(txt or image) of the produced result?

2023-12-04 09:50 UTC, safafa commented
@DanielePalombo [here](https://github.com/nebulab/failing_spec_detector/commit/f6982c7e119863ae48fb24f572c3f1fa2795c364) I updated the Readme. I also added an example screenshot in the PR comment. Or are you suggesting adding an example in the Readme file?

2023-12-04 09:54 UTC, DanielePalombo commented
> @DanielePalombo [here](https://github.com/nebulab/failing_spec_detector/commit/f6982c7e119863ae48fb24f572c3f1fa2795c364) I updated the Readme. I also added an example screenshot in the PR comment. Or are you suggesting adding an example in the Readme file?

In the README file it would be better so the purpose and the result will be more clear

2023-12-04 10:13 UTC, safafa commented
> > @DanielePalombo [here](https://github.com/nebulab/failing_spec_detector/commit/f6982c7e119863ae48fb24f572c3f1fa2795c364) I updated the Readme. I also added an example screenshot in the PR comment. Or are you suggesting adding an example in the Readme file?
> 
> In the README file it would be better so the purpose and the result will be more clear

[Done ](https://github.com/nebulab/failing_spec_detector/commit/eec6e0d30e4ff44a25372eaabd888a14f8f14d3f), wdyt?

2023-12-04 11:31 UTC, DanielePalombo approved these changes

2023-12-04 15:45 UTC, merged